language: node_js
node_js:
- '5'
deploy:
  - provider: releases
    api_key:
      secure: ScqKkkZ1Ss87TWFzcm/JqIlYXiUYJ4F6eHm+z6DmlE3ymEaW1qazAewSmzK9K085QhPQDwObCubV8ituMZiAlaUXjS6C9x0zkyA4bMNrIL9p+xb/BvdP7KLu+y7u5iBzBkEj0fdS7sdq1p3JVKNOn+GxG7HpSZ3Y6qstDcVfvNaMSZoGnNQ96xbIei+ThLiCTeFZjwO37h5Nl9I22c+2yOebxtEEpL52XkS6LbBwTrpPEmlsRYZny3W6P1pv2PJZPXF34nbRe+MxObMxi/XWWxztXG8sMDp+wtsxPy24kNXM8KAFkdCPcuM+T1rZfWmIThpWlL4uiLZmrYto+xNPTFrkygGVoq9e6n6BSLBQW/FaSyQ5cD0nuO11tKYAzOygvyUg38lXM6dNIAHzP4fiumM9avHU/4MVuRRFApauq4OSwTTYOZBUfMNDrDztzx7+y/Ha3P1Z//yfisYVT/TNjX58tKjtebQkecpC6VQfb6ydH1qPUMfv4mTJaNxtROkOG/idJdOsXIUgxkfo0iCU6Wc5GZTa6Sb+Qaqi6LKHcwBuVP49nProqqWL0FFezePLY8cWkGghVbRL6rgrT9OwiXVQdovs+BEFv+FBpSzUwyjz7o4E2Tx0MgSC59fskckh+0BW67SBC59qbFLIGPZp4I2FA5paadrkNo2HWNzrJQU=
    file: dist/lightogram.js
    skip_cleanup: true
    on:
      repo: tdukart/lightogram
      tags: true
  - provider: npm
    email: tdukart@aloftinteractive.com
    api_key:
      secure: Yrktz99xguzpmCIF4VG7SojOUrj2xGBng+zoW64uDf6D1kidiFTycSUckPdj/qYAKWLSQzAXbUznebUa2haD2LGoEc5KmSdWwKzFMMlZIpzPCSEbPDe6tt16fTCx18tiRwkgLC0pxerkEnZXalFqNWnYvT5xAgzjQFil06tO2ixRM+yziSz/UMWRcmBUCMioNeoGwHOoFhFW8K0ycrIrvDY0HhBXQCvg8qnevlrJZfALY/+UeMb5CjRCjKOwE0OXxASGQV/XBhmfVt8DhhkC4cHWRhwYql/bzQ9eZTe/nuZbK+dyGtFcvc84wB4Nn52rF4DL48efNjF7daJbuO64+1DcGKu6LgmBzZs3FUo+9ObUKFMW/MtST5J/zHaPVzN0wviUNpruZmA8CEv/ySCzVWPl2A3cayd76OkJIzSaCCxXW3w9lDLi0408gp3GTjaHtZqmDGYN01oRIsHnp3K750JdBPMzWGC1BXaJJcqXqVhT7uJI1m0Iq5Do17rztNHYen/VCyH3BYkDq30S6KrJjXYvXAVZwb6WH9L2Y81X6z/55g4h3NTmutrzz2yYp6RQEERzjckMZ6p8fnGCKGu2/551l2FukmSVL+ULQ/Izk4Oxya2sIquHSIl65pPCddUGKioDdVagHhvWBZ45yTOaduW66cD0qMJiaPByyvM8Tak=
    on:
      tags: true
      repo: tdukart/lightogram
